name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # This runs when you push to main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # Use the latest supported version
          bundler-cache: true

      - name: Install Jekyll and Dependencies
        run: |
          gem install jekyll bundler
          bundle install

      - name: Build Jekyll Site
        run: bundle exec jekyll build

      - name: Deploy to 'gh-pages'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
